version: "3.9"

services:
  yt-dlp-api:
    image: yt-dlp-api
    container_name: yt-dlp-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DOWNLOAD_DIR: /downloads
      # aktifkan kalau pakai cookies
      # COOKIES_FILE: /cookies/cookies.txt
    volumes:
      - ./downloads:/downloads
      # - ./cookies:/cookies
