version: "3.9"

networks:
  internal-net:
    external: true

services:
  redis:
    image: redis:7-alpine
    container_name: yt-dlp-redis
    environment:
      TZ: Asia/Jakarta
    restart: unless-stopped
    networks:
      - internal-net
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  yt-dlp-api:
    build: .
    container_name: yt-dlp-api
    restart: unless-stopped
    environment:
      TZ: Asia/Jakarta
      REDIS_URL: redis://redis:6379/0
      ROLE: api # WORKER MODE

      # API TIDAK BOLEH PROSES BERAT
      ENABLE_DOWNLOAD: "false"

      DOWNLOAD_DIR: /data/downloads
      COOKIES_PATH: /data/cookies/cookies.txt

    volumes:
      - downloads_data:/data/downloads
      - cookies_data:/data/cookies
      - assets_data:/data/assets
    networks:
      - internal-net
    depends_on:
      - redis

  yt-dlp-worker:
    build: .
    container_name: yt-dlp-worker
    restart: unless-stopped
    environment:
      TZ: Asia/Jakarta
      ROLE: worker # WORKER MODE
      REDIS_URL: redis://redis:6379/0

      # ðŸ”¥ QUEUE MODE
      WORKER_CONCURRENCY: "1" # 1 job = 1 yt-dlp / ffmpeg

      AUTO_DELETE_LOCAL: "true"
      CLEANUP_MAX_AGE: "7200"
      MINIO_STRICT: "true"

      DOWNLOAD_DIR: /data/downloads
      COOKIES_PATH: /data/cookies/cookies.txt
    volumes:
      - downloads_data:/data/downloads
      - cookies_data:/data/cookies
      - assets_data:/data/assets
    networks:
      - internal-net
    depends_on:
      - redis

volumes:
  downloads_data:
  cookies_data:
  assets_data:
  redis-data:
