version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  yt-dlp-api:
    build: .
    restart: unless-stopped
    environment:
      ROLE: api
      REDIS_URL: redis://redis:6379/0
      MINIO_SECURE: "false"

  yt-dlp-worker:
    build: .
    restart: unless-stopped
    environment:
      ROLE: worker
      REDIS_URL: redis://redis:6379/0
      AUTO_DELETE_LOCAL: "true"
      CLEANUP_MAX_AGE: "7200"
      MINIO_SECURE: "false"

