version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio:/data
    restart: unless-stopped

  yt-dlp-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      ROLE: api
      REDIS_URL: redis://redis:6379/0
      DOWNLOAD_DIR: /downloads
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: videos
      MINIO_PUBLIC_BASE_URL: http://localhost:9000/videos
      AUTO_DELETE_LOCAL: "true"
    volumes:
      - ./downloads:/downloads
    depends_on:
      - redis
      - minio

  yt-dlp-worker:
    build: .
    environment:
      ROLE: worker
      REDIS_URL: redis://redis:6379/0
      DOWNLOAD_DIR: /downloads
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: videos
      MINIO_PUBLIC_BASE_URL: http://localhost:9000/videos
      AUTO_DELETE_LOCAL: "true"
      CLEANUP_MAX_AGE: "7200"   # 2 jam

    volumes:
      - ./downloads:/downloads
    depends_on:
      - redis
      - minio
