version: "3.9"

networks:
  internal-net:
    external: true

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal-net
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  yt-dlp-api:
    build: .
    restart: unless-stopped
    environment:
      ROLE: api
      REDIS_URL: redis://redis:6379/0
      DOWNLOAD_DIR: /data/downloads
      COOKIES_PATH: /data/cookies/cookies.txt
    volumes:
      - downloads_data:/data/downloads
      - cookies_data:/data/cookies
      - assets_data:/data/assets
    networks:
      - internal-net
    depends_on:
      - redis

  yt-dlp-worker:
    build: .
    restart: unless-stopped
    environment:
      ROLE: worker
      REDIS_URL: redis://redis:6379/0

      WORKER_CONCURRENCY: "1"

      AUTO_DELETE_LOCAL: "true"
      CLEANUP_MAX_AGE: "7200"
      MINIO_STRICT: "true"
      DOWNLOAD_DIR: /data/downloads
      COOKIES_PATH: /data/cookies/cookies.txt

    volumes:
      - downloads_data:/data/downloads
      - cookies_data:/data/cookies
      - assets_data:/data/assets

    networks:
      - internal-net

    depends_on:
      - redis

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g

volumes:
  downloads_data:
  cookies_data:
  assets_data:
  redis-data:
